### ISSUE TITLE
[Feature Request]Display plot on selection for multiple widgets

### ISSUE THREAD

**Issue by onlytanmoy** [nfm886/skin.arctic.zephyr.2.resurrection.mod#1]
Hiya, I am the same user from Reddit who commented below in your reddit post 😊

![image](https://user-images.githubusercontent.com/48493659/120892225-230b2080-c605-11eb-92f3-06eb217b5ab6.png)

I am enjoying the skin so far, brilliant work! Just got one feature request for now, please refer the screen capture videos.

https://imgur.com/a/Sxq6oNV   - using heppen mod

Can you make the plot display appear like below when I select the movie title?
https://imgur.com/a/82Zhdod   - using AZ reloaded

Note: this works fine for single widget.

**Comment by nfm886** [comment]
I will think of it. There is a plans to make a new Home layout similar to "Vertical Multi-Widgets Netflix" one from AZ Reloaded. Maybe then I will think how to implement this and then I will need more explanation how it should works. But for now there is a lot of other things to do :)

**Comment by onlytanmoy** [comment]
Thanks for your response mate. Yeah that is fine no rush.
The main reason I switched from AZ Reloaded to AZ2 heppen mod is due to the fact that adding the movies to my Trakt user lists from the movie widgets works flawlessly in your skin and that is absent in AZ Reloaded so please don't break that awesome feature :)

**Comment by nfm886** [comment]
Thing likes to break hehe ^^
Joking. But to be serious, if something will broke please let me know! :)

**Comment by nfm886** [comment]
Hey @onlytanmoy 
I'm happy to say, introduced new home layout stylized on Netflix (just a bit^^). Maybe you should check this out since it have similar behavior with multiple widgets to this one from AZ: R :)
Please download this .zip file: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip
Or wait for an update but I don't know if I will push this update today, because this require some tests before ;)

**Comment by onlytanmoy** [comment]
@nfm886 Just now tested with the .zip, this looks really great and aligned to my expectation 😍
However, I noticed a glitch, the plot info, rating etc overlaps when I click on a movie poster from my widget, please refer the screen capture you will understand 

https://imgur.com/a/mlD0elZ

**Comment by nfm886** [comment]
Oh! I know about it but forgot to fix it before push :P will make an update when home :)

**Comment by onlytanmoy** [comment]
Updated to v0.3.9, the overlapping issue is gone but the play button is no longer working for the movies in DialogVideoInfo.

**Comment by nfm886** [comment]
Hey,
Since we added new layouts with this behavior can we close the ticket? :)

**Comment by onlytanmoy** [comment]
Indeed :) I got update notification in Kodi for v0.4.1, did that. Just the play thing not working for DialogVideoInfo but we do have a separate ticket for that :) happy to close this. Thank you.
