### ISSUE TITLE
Pull from skin.arctic.zephyr.2?

### ISSUE THREAD

**Issue by mechevarria** [nfm886/skin.arctic.zephyr.2.resurrection.mod#10]
Would you be able to get the last commits from the main skin.arctic.zephyr.2 merged in? I had made some commits for another view for AEL to skin.arctic.zephyr.2 master and it would be great if they got ported over

https://github.com/jurialmunkey/skin.arctic.zephyr.2/commits?author=mechevarria

Its the latest 3 commits 190, 222, and 237

Thanks!

**Comment by nfm886** [comment]
Hmm... Weird, because it should be there since this mod uses pkscout as a base and pkscout mod uses latest version from jurialmunkey. Maybe I'm wrong. I will try to implement this but I never messed with AEL before :)

**Comment by mechevarria** [comment]
I forked the repo too. I might try to merge the code as well and do a pull request. I think files that have a comment of 'initial upload' could just be drag and drop and the others would have to be more careful merging

**Comment by nfm886** [comment]
Would be awesome to see a pull request. Also please leave some comments on code to better understanding what it does. I never messed with AEL so I don't even know how I should test it ^^

**Comment by nfm886** [comment]
Hey again!
Maybe today or tomorrow I will make a new branch for testing AEL view. I will tell you when it's done :)

**Comment by mechevarria** [comment]
Merged a long time ago. Thanks man! Should have closed this

**Comment by nfm886** [comment]
Thank you for your contribution :)
