### ISSUE TITLE
TV Shows says None (None) scraping...

### ISSUE THREAD

**Issue by onlytanmoy** [nfm886/skin.arctic.zephyr.2.resurrection.mod#18]
Hiya, looks like got a new bug :) Please watch the screen record.
https://www.veed.io/download/bc11438c-ed5d-4cfe-b85c-5503402407e0

Unable to play any of the next episodes due to this issue! Movies work fine though.

**Comment by nfm886** [comment]
Ahh... Right. I know what causing it. Tomorrow will make a fix :)

**Comment by onlytanmoy** [comment]
ok cool 👍🏻 have a good night mate.

**Comment by nfm886** [comment]
Playing tv shows should be fixed. Please test it: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip and give me a feedback.
Also there may be some issues playing episodes. I will try to fix it again.
Please make sure everything is working fine. After yesterday's changes some people reported broken play button. It's probably fixed already.

**Comment by onlytanmoy** [comment]
Sure, I will test after one hour or so and report back.
I plan to cover the below scenarios:
Home screen widget- Playing Movie & Trailer, Playing Next episode, Playing TV Show Trailer
Similar movies - Playing Movie & Trailer

**Comment by nfm886** [comment]
Episodes may not works for now.
I will be back to work in about 3-4 hours. I have to go out :)

**Comment by onlytanmoy** [comment]
Home screen widget:
Playing Movie & Trailer: Both works

Similar Movie: Playing Movie: Works
Trailer: Does NOT work, just shows blank info screen as below
![Kodi_20210621_142409](https://user-images.githubusercontent.com/48493659/122769340-653a9000-d29c-11eb-9d0a-01cf1a90ba34.png)

I will test TV shows in some time, please fix trailer not working for similar/related movies.

**Comment by onlytanmoy** [comment]
Ok, so I tested TV shows now, episode is not working as you already know :)
Trailer working fine.
Browse button does not work. When I click it, I am thrown back to home screen, please refer screen record.
https://imgur.com/a/pM9yCFM

**Comment by nfm886** [comment]
Yes, I noticed it too :P
Will be back with a fix I hope ^^

**Comment by nfm886** [comment]
I bring back previous behavior to play button since it broke a lot of things :/
Please test it how much you can and report me back how it works.
I think for now it will stay as it is. There is some more things to do and do not want to waste too much time on one thing. I will back to it for sure anyway :)

**Comment by onlytanmoy** [comment]
@nfm886 didn't quite understand your comment, you want me to test a new version or what? I have pinged you in Reddit chat to clarify :)

**Comment by onlytanmoy** [comment]
Tested the new zip, please see my detailed analysis below :)

Home screen widget:-
a. Playing Movie: works
b. Playing Trailer: works

Similar Movie:-
a. Playing Movie: Does NOT work (please see screen record)
    https://www.veed.io/download/acf09b5d-f090-46f1-a419-f71a574e43c7
b. Playing Trailer: works

TV Show:-
a. Playing Trailer: works
b. Playing Episode: works

Recommended TV Show:-
a. Playing Trailer: works
b. Episode Browse: works (screenshot below)
![Kodi_20210621_201016](https://user-images.githubusercontent.com/48493659/122816065-2a515000-d2ce-11eb-8b66-4569bfff4c9f.png)

**Comment by nfm886** [comment]
Hey,
I made some changes to play button. Please test it as much as you can in every scenario :)
Zip: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip

**Comment by onlytanmoy** [comment]
Cool, I will cover all the above scenarios as I tested earlier and report back in some time :)

**Comment by nfm886** [comment]
Browse button is fixed. Please download zip file again. I forgot about it before :>

**Comment by onlytanmoy** [comment]
Browse was fixed in the version I tested yesterday :) haven't you seen my comment with the screenshot?

b. Episode Browse: works (screenshot below)

**Comment by onlytanmoy** [comment]
I tested with the zip from 19 mins back, please see my findings below

From Home Screen widget:-
a. Playing Movie: works
b. Playing Trailer: works

Similar Movie:-
a. Playing Movie: works
b. Playing Trailer: works

TV Show:-
a. Playing Episode: works
b. Playing Trailer: works

Recommended TV Show:-
a. Playing Trailer: works
b. Episode Browse: Does NOT work

**Comment by nfm886** [comment]
Ok, I will take a closer look.

**Comment by onlytanmoy** [comment]
Tested with the latest zip, everything working great.
You did a cracking job with this skin mate, so kudos to that, cheers!
