### ISSUE TITLE
[BUG] Unable to select highlight colour

### ISSUE THREAD

**Issue by Manuel5cc** [nfm886/skin.arctic.zephyr.2.resurrection.mod#19]
I have been using this skin for a few days. Recently swapped from the pkscout version (apparently abandoned) and I had the same problem with that one. When trying to select the highlight colour, it should open a selection window but nothing happens (no window, no error message...).

![highlight](https://user-images.githubusercontent.com/21358555/122786095-3b8d6300-d2b4-11eb-836d-e46686623b76.JPG)

**Comment by nfm886** [comment]
For some reason it does not install script.skin.helper.colorpicker I think. Please go to skin settings > manage dependencies and click on script.skin.helper.colorpicker (first on the list). It should install this dependency and it should works as expected.

**Comment by Manuel5cc** [comment]
Looks like it was installed but not properly, so I just had to reinstall it manually and now it is working.
