### ISSUE TITLE
Progress circle bad positioning

### ISSUE THREAD

**Issue by Manuel5cc** [nfm886/skin.arctic.zephyr.2.resurrection.mod#21]
After the last update, the progress "bar" is positioned incorrectly. It happens in all screen sizes and OS (I have tested it on Windows and Android).
![Inkedscreenshot00000_LI](https://user-images.githubusercontent.com/21358555/123514926-9ac4ec00-d695-11eb-9050-71038523ad69.jpg)
![screenshot00000](https://user-images.githubusercontent.com/21358555/123514927-9bf61900-d695-11eb-88e4-3b4954b2db66.png)

**Comment by nfm886** [comment]
Thanks, I will closer look on this. I hope it will be fixed with today's update in the evening.

**Comment by nfm886** [comment]
Is this happening when your library is scanning? I need to reproduce this situation to better understanding it :P

**Comment by Manuel5cc** [comment]
I have ony noticed it when doing a library scan. I can test other cases if needed.

**Comment by nfm886** [comment]
No need. Thanks I know where to looking :)

**Comment by nfm886** [comment]
From what I see it is positioned OK: https://imgur.com/FdWs9PJ
Could you please tell me how to trigger this type of progressbar?

**Comment by Manuel5cc** [comment]
Simply by updating (scanning) the library (I have a dedicated shortcut for it). Not sure if it affects it but I do have "minimal busy loader" option activated.

**Comment by nfm886** [comment]
I'm using Minimal busy loader too. What shortcut is it? :)

**Comment by nfm886** [comment]
We can speak on discord or reddit chat if you want.

**Comment by Manuel5cc** [comment]
I have the shortcut in a submenu under "Settings". The command that triggers it is: UpdateLibrary(video,,true)
![2021-06-26-16-52--1920-x-1080-EbFka1uNgP](https://user-images.githubusercontent.com/21358555/123516928-e8922200-d69e-11eb-92a8-b1244818feb3.png)

**Comment by nfm886** [comment]
Unfortunately I can't reproduce this bug :/ For me it works. Please download this zip file and install this skin from zip: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip
I hope it will fix if not we will investigate this issue further :)

**Comment by nfm886** [comment]
Ahh, ok. You are using Basic Home Layout. I think it's fixed with commit made some minutes ago :)
If you will download this zip file, it should be already fixed :)

**Comment by Manuel5cc** [comment]
> Ahh, ok. You are using Basic Home Layout. I think it's fixed with commit made some minutes ago :)

Oh yeah, sorry, I forgot to mention that. Thanks, I'll wait until it's updated in the official repo but I'm sure it works fine now!

**Comment by nfm886** [comment]
OKI :) 
I will push an update about 20:00 GMT+2 so about 3 hours later from now ;)

**Comment by nfm886** [comment]
And sorry for the issue ^^

**Comment by Manuel5cc** [comment]
> And sorry for the issue ^^

It's ok! I'm just glad to help improve this skin!

**Comment by nfm886** [comment]
Hey @Manuel5cc, just pushed an update :)
Please update and give me feedback if everything is OK now ;)

**Comment by Manuel5cc** [comment]
Yep it is displaying correctly now :)

**Comment by nfm886** [comment]
Uff :)
