### ISSUE TITLE
Bad colors in tv osd with dark theme

### ISSUE THREAD

**Issue by notoco** [nfm886/skin.arctic.zephyr.2.resurrection.mod#22]
![screenshot00000](https://user-images.githubusercontent.com/36659110/123515043-466e3c00-d696-11eb-8c25-2f233008b6af.png)

**Comment by nfm886** [comment]
I tested it yesterday and though it's fixed. 
Please tell me what settings you are using. Which Home Layout and which Color themes (from Interface settings). I will fix it right now and push with today's update in the evening :)

**Comment by nfm886** [comment]
Ok. It is fixed now. I just used static values for this instead of dynamic. I will push update a bit later :)

**Comment by nfm886** [comment]
Just pushed an update with a fix. I think we can close the issue :)
