### ISSUE TITLE
Nakładanie obrazów. 

### ISSUE THREAD

**Issue by Katapulta** [nfm886/skin.arctic.zephyr.2.resurrection.mod#26]
Może po polskim teraz. Będzie wygodniej. Znalazłem taki mały myk w najnowszej wersji... Nie mam możliwości zrobienia screena w tej chwili więc wybacz. Menu pionowe ( to po lewej stronie co się wyświetla , nigdy nie pamiętam jak się to poprawnie nazywa ) . Jak ustawię tapety / tła dla danej kategorii i np zmienię sobie w ścieżce Kodi\addons\skin.arctic.zephyr.2.resurrection.mod\media\common  tła : bg.jpg i black-back.png to nakładają się na obraz tapet w menu. Czyli to jest w standardzie ten efekt "przymglenia" tapety w tym widoku menu. Pytanie - czy da się to jakoś obejść, żeby obrazy się nie nakładały na siebie ( może gdzies jest opcja ręcznej edycji )

**Comment by nfm886** [comment]
Zapewne wiem o co Ci chodzi. Jednak dobrze byłoby zobaczyć screenshot, żeby się upewnić.
Jeśli chcesz się bawić to możesz spróbować edytować te linie: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/blob/main/1080i/Includes_Global.xml#L66-L140
One w głównej mierze odpowiadają za tło. 
Póki co bardziej pomóc chyba nie mogę, dopóki nie zobaczę skrina. Nie potrafię sobie jakoś tego wyobrazić :P

**Comment by Katapulta** [comment]
Tak wygląda jak wrzucę sobie / podmienię tło w menu skina 
https://i.imgur.com/fLrlQ7M.png
A tak wygląda menu główne - ta sytuacja z tych dwóch plików o których ci pisałem wyżej 
https://i.imgur.com/pssvS9e.png
https://i.imgur.com/r46e5bm.png

Kwestia czy da się to jakoś wykluczyć - nawet sam dla siebie jak bym chciał. Żeby podmiana tła w menu skóry nie wiązała się z tym ze będzie się to nakłądało na menu główne - pionowe po lewej. W poziomym to ne występuje. 

https://i.imgur.com/RL8ozlz.jpeg

**Comment by nfm886** [comment]
Aha rozumiem. Czyli chcesz wyłączyć ten czarny overlay?
W sumie mogę zrobić przełącznik do wyłączania/włączania go, bo nie jesteś jedyną osobą, której to by się przydało :P

p.s. sorki, że odpisuję dopiero teraz ;)

**Comment by Katapulta** [comment]
> 
> 
> Aha rozumiem. Czyli chcesz wyłączyć ten czarny overlay?
> W sumie mogę zrobić przełącznik do wyłączania/włączania go, bo nie jesteś jedyną osobą, której to by się przydało :P
> 
> p.s. sorki, że odpisuję dopiero teraz ;)

Easy :) Nigdzie się nie pali :) Ale prawdę mówiąc trochę jak dla mnie osobiście jak się ze sobą tak mieszają dwa obrazy - wygląda to kiepsko :P Więc gdyby była opcja - było by super.

**Comment by nfm886** [comment]
Ok, za chwilę postaram się wdrożyć przełącznik i dam ci zipa do testów :)
Później fajnie by było jakbyśmy wrócili do Twojego poprzedniego ticketa, bo tamto też chciałbym zamknąć powoli ;)

**Comment by nfm886** [comment]
Dodałem przełącznik, znajdziesz go w skin settings > background > disable overlay.
Proszę przetestuj tego zipa: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip i daj znać czy o to chodziło :)

**Comment by Katapulta** [comment]
> 
> 
> Dodałem przełącznik, znajdziesz go w skin settings > background > disable overlay.
> Proszę przetestuj tego zipa: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip i daj znać czy o to chodziło :)

Nie do końca... aczkolwiek... Sama opcja i tak wydaje mi się że daje fajniejszy efekt , tapety nie są takie zaciemnione chyba ze to moje złudzenie. Podmiana tych dwóch plików o których pisałem wyżej - zmiana background w menu samej skóry , bo takie czorne i ciemne było . Tak to wyglada 
https://i.imgur.com/HgLffDw.png
https://i.imgur.com/xoWIieJ.png

Tyle że właśnie od którejś aktualizacji zaczęło to przebijać w tym widoku menu i wygląda jak taki "znak wodny" 
https://i.imgur.com/sg4Gi2h.jpeg

**Comment by nfm886** [comment]
Używasz menu wertykalnego z "dark with dark dialogs" schematem kolorów? Muszę u siebie odtworzyć całą sytuacje :P
Przy okazji, masz może discorda i chwile czasu? Byłoby łatwiej się dogadać i może jeszcze bym puścił poprawkę z dzisiejszą aktualizacją ;)

**Comment by Katapulta** [comment]
> 
> 
> Używasz menu wertykalnego z "dark with dark dialogs" schematem kolorów? Muszę u siebie odtworzyć całą sytuacje :P
> Przy okazji, masz może discorda i chwile czasu? Byłoby łatwiej się dogadać i może jeszcze bym puścił poprawkę z dzisiejszą aktualizacją ;)

Kurde no nie używam discorda prawdę mówiąc :D A menu wertykalne - tak w takim setupie, najładniejsze jak dla mnie + jeszcze te kolory z gradientem... robi robotę :) A takie smaczki akurat cieszą moje oko :) Tyle ze po każdej aktualce trzeba je na nowo ustawiać bo sie resetuje do domyślnego :P

**Comment by nfm886** [comment]
Ok, chyba udało mi się odtworzyć problem. Chodzi dokładnie o to: https://imgur.com/jJVgLl0 tak?
Ogólnie podmiana tła poprzez pliki nie jest najlepszym pomysłem, bo właśnie wychodzą takie kwiatki. Muszę pomyśleć w jaki sposób to najlepiej rozwiązać.

**Comment by nfm886** [comment]
Ogólnie to myślę teraz, w jaki sposób zaimplementować podmianę tła, aby można było to zrobić prosto z ustawień. Wtedy nie będzie trzeba po każdej aktualizacji ich podmieniać. W dodatku może uda się rozwiązać ten problem po drodze.

**Comment by nfm886** [comment]
Sprawdź proszę tego zipa: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip czy problem z nakładaniem się dalej występuje po wyłączeniu background overlay.

**Comment by Katapulta** [comment]
> 
> 
> Ok, chyba udało mi się odtworzyć problem. Chodzi dokładnie o to: https://imgur.com/jJVgLl0 tak?
> Ogólnie podmiana tła poprzez pliki nie jest najlepszym pomysłem, bo właśnie wychodzą takie kwiatki. Muszę pomyśleć w jaki sposób to najlepiej rozwiązać.

Jesli jako tło danej kategorii ustawiłeś ten sam obraz na jaki podmieniłeś pliki bg.jpg i black-back.png to może to być ten efekt o który mi chodzi. Nagrałem "na szybko" wizualizację u siebie. Kategoria BAJKI - ustwiłem tło na całe białe żeby było widać lepiej  czyli tapeta "w kolorze białym" zassana z sieci. Podmieniłem te dwa pliki zeby zmienić kolor tła w menu / w ustawieniach skóry. Później na filmie widzisz efekt - tło ustawień / skina nakłada się na tło ustawionej tapety w tym układzie menu. Zwróć uwagę jak "klikam w ustawienia interfejsu" - i na zmienione tło w tej sekcji, to pod kafelkami na tym przykłądzie jest słabiej widoczne więc tak ci to zobrazuję. https://streamable.com/kvrd6l

**Comment by Katapulta** [comment]
> 
> 
> Sprawdź proszę tego zipa: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip czy problem z nakładaniem się dalej występuje po wyłączeniu background overlay.

a ok, już sprawdzam, jeszcze napisałem ci / nagrałem :P już to wrzucam do siebie.

**Comment by Katapulta** [comment]
Uuu ten zip w ogóle coś popsuł. Kompletnie sie po aktualizacji nie odpala. Czarny ekran, później nic. Zniknęło menu , wszystko :P

**Comment by nfm886** [comment]
Zamknij kodi i odpal ponownie :)

**Comment by nfm886** [comment]
Nic wielkiego nie zmieniałem, więc spokojnie będzie hulało :D

**Comment by Katapulta** [comment]
No powróciło do tego co było i dalej wyglada to tak samo :P https://i.imgur.com/Vl2XJn5.png Może zostawmy to :P nie jest to aż tak niezbędne... a moze kiedyś z czasem :P

**Comment by nfm886** [comment]
Spokojnie, zaraz to ogarniemy :)
A mógłbyś usunąć folder ze skórką i z ustawieniami skórki? I wtedy ponownie zainstalować skórkę.

**Comment by Katapulta** [comment]
Jasne. Już działam.

**Comment by nfm886** [comment]
U mnie obrazy już się nie nakładają mimo podmienionego bg.jpg i black-back.png

**Comment by nfm886** [comment]
Jedyny minus jeszcze jaki widzę to obrazy się mocno skalują w górę jak mają inną rozdzielczość przez co nie wygląda to zbyt ładnie. Ale to poprawie wraz z wprowadzeniem opcji zmiany tła :D

**Comment by Katapulta** [comment]
Super, teraz już się nei nakładają faktycznie. Rewelka. Co do skalowania - prawdę mówiąc nie zwracalem na to uwagi. Mam tła / tapety w bardzo dużej rozdzielczości , od 1080p do 4k więc prawdę mówiac nie zauważyłem żadnego skalowania :P

**Comment by nfm886** [comment]
No i elegancko :)
W takim razie biorę się za implementację zmiany tła. Myślę, że będzie gotowe wraz z wieczorną aktualizacją. Masz jeszcze jakieś pomysły/sugestie? Chętnie wysłucham ;)

**Comment by Katapulta** [comment]
Jedynie w sumie o jednej ci już pisałem - to okno capcha które wyskakuje i nei można go odczytać :P w przypadku Internetowej i wtyczki od mbebe problem jest taki ze są 3 próby :P później dostajesz bana :P https://streamable.com/bfkv4x 

No i może to co ktoś ci już pisał kiedyś - o braku możliwości "cofnięcia się" - w przypadku obsługi z kompa na przykład - trzeba użyć klawisza backspace - nie ma pozycji "wstecz" czy też tych "trzech kropek" do powrotu. Ty na przykładzie fanfilm https://streamable.com/qzoht6
Ale to drobiazgi. 

Jak dla mnie ten skin jest już tak odpicowany i doje**any że osobiście nic więcej mi nei trzeba do szczęścia :) Po prostu wymiata :)

**Comment by nfm886** [comment]
Sprawdzę ten problem z captcha. Może napiszę na GH mbebe i będzie w stanie współpracować to by się jakoś rozwiązało ten problem.

Co do możliwości cofnięcia to zapomniałem o tym kompletnie :P Muszę sprawdzić w innych skórkach jak to jest rozwiązane. Większość rzeczy, które miałem do zrobienia już zostały zrobione, więc zajmę się znowu zamykaniem ticketów na GH :)

> Jak dla mnie ten skin jest już tak odpicowany i doje**any że osobiście nic więcej mi nei trzeba do szczęścia :) Po prostu wymiata :)

Nawet nie wiesz jak miło czytać takie opinie ^^ To napędza do pracy jeszcze bardziej i aż chce się rozwijać tą skórkę :D 

No i  tym pozytywnym akcentem zamkniemy tego ticketa ^^ Jak będę poprawiał captche i problem z cofaniem to będę pisał w Twoim poprzednim issue, tam będzie rozpracowywać problemy :)
Dzięki i pozdrawiam :D Close
