### ISSUE TITLE
Start failure

### ISSUE THREAD

**Issue by staticEndeavour** [nfm886/skin.arctic.zephyr.2.resurrection.mod#31]
I have an issue where, when switching to Arctic Zephyr 2, it hands on the loading screen.

This happens directly after installation, it goes to the splash pictured, 

https://ibb.co/ngfR5MW

and just keeps spinning. I have to kill the app to get out.

And then when I start the program again, the splash will come up, and just remain. It seems to still function underneath as when I restart, the library can still scan.

I've tried several full wipes and reinstalls of Kodi, but the same will happen every time, and I'll have to completely wipe and reinstall Kodi. 

I'm on Kodi v19.0. Ubuntu 21.04 with Plasma. It's a relatively fresh OS install.

**Comment by nfm886** [comment]
Hi! Thanks for reporting the issue.
I though it's fixed since today's morning. I pushed an update which should fix this issue. Please tell me, which version you see in heppen's repository?

**Comment by staticEndeavour** [comment]
New repo sorted it. Nice job by the way, looks great.

Thanks very much.

**Comment by nfm886** [comment]
Glad to hear! So we can close this issue ;)
