### ISSUE TITLE
Netflix layout

### ISSUE THREAD

**Issue by deyooluv** [nfm886/skin.arctic.zephyr.2.resurrection.mod#33]
You are doing an amazing work on the flix layout. I have a suggestion that will make the Flix layout better.
For multiple widget on the home screen it looks better when there is just one widget appearing per scroll or screen(upward or downward) instead of two widgets appearing. Fanart will become bigger and the UI will be better looking when you take this suggestion. I have a screenshot so you have a better idea of what I mean
![Screenshot_20210710-125626_Kodi](https://user-images.githubusercontent.com/73711940/125173860-cad4ba80-e17e-11eb-92cb-2cb627770619.jpg)

**Comment by nfm886** [comment]
I started with one row for widgets. People wanted second row to be visible too^^
Now I'm trying to follow a bit original Netflix design: https://imgur.com/eISPaOp
Maybe I will just put those rows a bit lower. Hmm... 
It's hard to please everyone :P

**Comment by deyooluv** [comment]
> I started with one row for widgets. People wanted second row to be visible too^^
> Now I'm trying to follow a bit original Netflix design: https://imgur.com/eISPaOp
> Maybe I will just put those rows a bit lower. Hmm...
> It's hard to please everyone :P

This looks amazing and the UI looks alot better with the addition of rating. Thr fanart widow will look a lot bigger as well.
Also please can you make a Flix view as well so when the next page item for a widget in the home screen is pressed, the view can continue to the next page

**Comment by nfm886** [comment]
> We are close to final product :)
> Please take a look on it: https://streamable.com/glyr19 and this: https://streamable.com/rztdr0
> If you want to test this out without waiting, please download this zip file: https://github.com/nfm886/skin.arctic.ze...x-view.zip and give me a feedback!
> I think I will push an update maybe today in the evening or tomorrow :)


> Also please can you make a Flix view as well so when the next page item for a widget in the home screen is pressed, the view can continue to the next page

Maybe in the near future I will introduce this option.

**Comment by deyooluv** [comment]
A0

> > We are close to final product :)
> > Please take a look on it: https://streamable.com/glyr19 and this: https://streamable.com/rztdr0
> > If you want to test this out without waiting, please download this zip file: https://github.com/nfm886/skin.arctic.ze...x-view.zip and give me a feedback!
> > I think I will push an update maybe today in the evening or tomorrow :)
> 
> > Also please can you make a Flix view as well so when the next page item for a widget in the home screen is pressed, the view can continue to the next page
> 
> Maybe in the near future I will introduce this option.

The new tweak on the home screen looks good. The plot on the second screen when you click on filmy is so long. For consistency purpose it would be a great idea to fix the long plot and the position of the rating as well to keep up with the Flix view outside of the home screen. I have attached a screenshot on the long plot
![Screenshot_20210711-091027_Chrome](https://user-images.githubusercontent.com/73711940/125200431-5eae9100-e228-11eb-9f60-8aadd561f8d5.jpg)

**Comment by nfm886** [comment]
Yes, I will do this :)
First I want to introduce Flix view and then I will play around with Flix Showcase view.
