### ISSUE TITLE
Weird highlight glitch on menu (vertical and horizontal)

### ISSUE THREAD

**Issue by OsoaGitHub** [nfm886/skin.arctic.zephyr.2.resurrection.mod#41]
![image](https://user-images.githubusercontent.com/33041004/125834852-66a7f316-f459-4b34-a420-1f80d0fe4d11.png)
I've tested this on vertical and horizontal mode and it happens in both.

**Comment by nfm886** [comment]
What version you are using? Horizontal should be fixed now.
I know about vertical but have not enough time to fix it yet.

**Comment by OsoaGitHub** [comment]
I'm on 0.6.4, there is no available updates on my end

**Comment by nfm886** [comment]
Ok. I'm working on it right now.

**Comment by nfm886** [comment]
Please download this zip file https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/testing.zip and test if issue is fixed.

**Comment by OsoaGitHub** [comment]
working now, thanks

**Comment by nfm886** [comment]
Ok, so we can close the issue.
