### ISSUE TITLE
Rotten tomattoes and imdb ratings not working also the vote counts

### ISSUE THREAD

**Issue by Mr-Barillas** [nfm886/skin.arctic.zephyr.2.resurrection.mod#53]
clean install on windows, tmb helper setup done.

* removed screenshot because of sensitive data *

![screenshot00001](https://user-images.githubusercontent.com/88249814/127749200-7b10748f-2440-417b-90fe-53cefcd32db8.png)

![screenshot00000](https://user-images.githubusercontent.com/88249814/127749157-8b4c7575-ba2a-4cdd-a119-cbb0771a0acb.png)

**Comment by nfm886** [comment]
In OMDb API key you need to enter only your key, not full URL. Just remove all the url and left string after apikey=

**Comment by Mr-Barillas** [comment]
hahaha no way, ill try right now.

**Comment by Mr-Barillas** [comment]
ir worked perfect. haha thanks man i spent a lot of time figuring that out. 
question, what files i have to edit to show imdb  count votes and movie description on info wall 2 , give me a clue thanks

**Comment by nfm886** [comment]
> question, what files i have to edit to show imdb count votes and movie description on info wall 2 , give me a clue thanks

You can enable debugging in skin settings, it will show you file name in specific view. Then just go to view you would like to edit, and you will see it's name in top left corner.

**Comment by Mr-Barillas** [comment]
thanks man. blessings. now i have something to do this weekend. ;) enjoy

**Comment by nfm886** [comment]
> thanks man. blessings. now i have something to do this weekend. ;) enjoy

Good luck, my friend! :)
