### ISSUE TITLE
[Feature Request]Movie release year against the titles

### ISSUE THREAD

**Issue by onlytanmoy** [nfm886/skin.arctic.zephyr.2.resurrection.mod#8]
Hi, its me again :) 
In the home screen widgets will it be possible to populate the movie release year adjacent to the movie title in parenthesis like Deep Blue Sea 3 (2020) and not just Deep Blue Sea 3 ? I think this feature is present in Aura skin.

**Comment by nfm886** [comment]
Hi!
That's a good idea ;) It should be implemented soon, maybe will be available with next update.

**Comment by nfm886** [comment]
Added in latest main branch. You can test it by downloading this zip file: https://github.com/nfm886/skin.arctic.zephyr.2.resurrection.mod/archive/refs/heads/main.zip

It will be available with next update :)

**Comment by onlytanmoy** [comment]
Just now tested I can confirm this is working great 😍 many thanks mate.
Once the next update is rolled out will I get an update notification in Kodi? I have added your source URL via file manager.

**Comment by nfm886** [comment]
I found some issue. For example year is disappear from the DialogVideoInfo, so I have to find better implementation for this or find a golden mean :/

**Comment by onlytanmoy** [comment]
Ah right, I see that now, I did not test it to that level 😄
My query on the update - will I get notification in Kodi like other add-ons?

**Comment by nfm886** [comment]
Of course if you are using my repository. But keep mind after you installed it from .zip update may not works as before. Usually I'm updating this skin every day in the evening (EU time) if everything goes well ;)

**Comment by onlytanmoy** [comment]
Yes, I am using your repo in Kodi File manager. Now that I installed from the .zip file you gave me today you are saying I will not get update notifications any longer when a new version is available?

**Comment by nfm886** [comment]
Probably not, since it's from local file instead of repository. 

I hope I fixed previous issue with displaying year in DialogVideoInfo. If you can, please download .zip file again and do some tests ;)
After it, you can wait for next update, then uninstall skin and install it back from repository :)

**Comment by onlytanmoy** [comment]
Yes, just now tested, release years getting displayed in DialogVideoInfo 👌 thank you.
Please close this ticket :)

**Comment by nfm886** [comment]
Glad to hear, enjoy :)
